# filepath: c:\Users\sdellalibera\source\repos\chatbot\kubernetes\backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-backend
  template:
    metadata:
      labels:
        app: chatbot-backend
    spec:
      containers:
      - name: chatbot-backend
        image: acrdemopn.azurecr.io/chatbot-backend:latest
        imagePullPolicy: Always
        env:
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: 'true'
        - name: ASPNETCORE_URLS
          value: 'http://+:8080'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Production'
        - name: ALLOWED_ORIGINS
          value: 'http://chatbot-frontend,http://chatbot-frontend.default.svc.cluster.local,https://*.azurewebsites.net'
        resources:
          requests:
            cpu: '250m'
            memory: '512Mi'
          limits:
            cpu: '1000m'
            memory: '2Gi'
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: chatbot-backend
