# filepath: c:\Users\sdellalibera\source\repos\chatbot\kubernetes\frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
  labels:
    app: chatbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
      - name: chatbot-frontend
        image: acrdemopn.azurecr.io/chatbot-frontend:latest
        imagePullPolicy: Always
        env:
        - name: API_URL
          value: 'http://chatbot-backend' # Reference the backend service by its k8s service name
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: '100m'
            memory: '256Mi'
          limits:
            cpu: '500m'
            memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-frontend
spec:
  selector:
    app: chatbot-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: '/'
spec:
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: chatbot-frontend
            port:
              number: 80
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: chatbot-backend
            port:
              number: 80
