name: Deploy ChatbotAI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_CONTAINER_REGISTRY: acrdemopn.azurecr.io
  BACKEND_CONTAINER_NAME: chatbot-backend
  FRONTEND_CONTAINER_NAME: chatbot-frontend
  RESOURCE_GROUP: scaling-aks-demo-rg
  CLUSTER_NAME: aks-minimal-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.BACKEND_CONTAINER_NAME }}:${{ github.sha }}
        
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.FRONTEND_CONTAINER_NAME }}:${{ github.sha }}
        
    - name: Set up kubeconfig
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        
    # Update deployment yaml with current image tags
    - name: Update kustomization.yaml
      run: |
        cd kubernetes/
        sed -i "s|newTag: latest|newTag: ${{ github.sha }}|g" kustomization.yaml

    - name: Deploy to AKS
      run: |
        cd kubernetes/
        kubectl apply -k .
        
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/chatbot-backend
        kubectl rollout status deployment/chatbot-frontend
